import crypto from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import type { AssistantMessageEvent } from "@oh-my-pi/pi-ai";
import type { ExtensionAPI } from "@oh-my-pi/pi-coding-agent";

const BUCKET_MS = 100;
const WINDOW_MS = 1_000;
/**
 * Seed ratio, used until `omp-tokrate` has learned one for this model. It is
 * only a seed: measured medians run 2.3-3.9 bytes/token, so a session with no
 * calibration under-reports by about a third rather than being wrong by orders.
 */
const BYTES_PER_TOKEN = 4;
/** Ratios outside this band are provider bookkeeping artifacts, not text. */
const MIN_RATIO = 1.5;
const MAX_RATIO = 12;
/** A model's learned ratio changes at most once per message; re-stat rarely. */
const CALIBRATION_TTL_MS = 60_000;

/**
 * Version 2 adds `model`/`provider`. A reader that only knows v1 counts every
 * file as cloud tokens, which is what a v1 file always meant; a reader that
 * knows v2 can skip a locally served model, whose tokens the local inference
 * server has already counted at the GPU, and so avoid counting them twice.
 */
export interface TokenRateSample {
	version: 2;
	pid: number;
	/** Omitted, never null, when the stream event did not name one. */
	model?: string;
	provider?: string;
	updatedAt: number;
	buckets: Array<[number, number]>;
}

/** The attribution a stream event carries; `AssistantMessage` satisfies it. */
export interface TokenRateSource {
	model?: string;
	provider?: string;
}

/** Bytes per token for the model a delta was generated by. */
export type CharsPerTokenLookup = (model?: string, provider?: string) => number;

/** Rolling 100 ms output buckets; readers derive the live one-second rate. */
export class TokenRateBuckets {
	readonly #pid: number;
	readonly #charsPerToken: CharsPerTokenLookup;
	#buckets: Array<[number, number]> = [];
	#model: string | undefined;
	#provider: string | undefined;

	constructor(pid = process.pid, charsPerToken: CharsPerTokenLookup = () => BYTES_PER_TOKEN) {
		this.#pid = pid;
		this.#charsPerToken = charsPerToken;
	}

	/**
	 * `source` names the model this delta was generated by. The last named model
	 * wins: a mid-session model switch retires the previous one well before the
	 * one-second window it shares can matter, and an event that names nothing
	 * must not erase an attribution we already have.
	 */
	ingest(delta: string, now = Date.now(), source?: TokenRateSource): TokenRateSample {
		if (source?.model) this.#model = source.model;
		if (source?.provider) this.#provider = source.provider;
		const bucketAt = Math.floor(now / BUCKET_MS) * BUCKET_MS;
		const ratio = this.#charsPerToken(this.#model, this.#provider);
		const tokens = Buffer.byteLength(delta, "utf8") /
			(Number.isFinite(ratio) && ratio > 0 ? ratio : BYTES_PER_TOKEN);
		const last = this.#buckets.at(-1);
		if (last?.[0] === bucketAt) last[1] += tokens;
		else this.#buckets.push([bucketAt, tokens]);
		return this.snapshot(now);
	}

	snapshot(now = Date.now()): TokenRateSample {
		const cutoff = now - WINDOW_MS;
		while (this.#buckets[0]?.[0] < cutoff) this.#buckets.shift();
		return {
			version: 2,
			pid: this.#pid,
			...(this.#model === undefined ? undefined : { model: this.#model }),
			...(this.#provider === undefined ? undefined : { provider: this.#provider }),
			updatedAt: now,
			buckets: this.#buckets.map(([at, tokens]) => [at, tokens]),
		};
	}
}

function runtimeDirectory(): string {
	const base = process.env.XDG_RUNTIME_DIR || os.tmpdir();
	return path.join(base, "herd-token-rate");
}

function calibrationPath(): string {
	const override = process.env.OMP_TOKRATE_STATE;
	if (override) return override;
	const base = process.env.XDG_STATE_HOME || path.join(os.homedir(), ".local", "state");
	return path.join(base, "omp-tokrate", "calibration.json");
}

/** Median of a non-empty list; even counts average the middle pair. */
function median(values: readonly number[]): number {
	const sorted = [...values].sort((a, b) => a - b);
	const middle = sorted.length >> 1;
	return sorted.length % 2 === 1 ? sorted[middle] : (sorted[middle - 1] + sorted[middle]) / 2;
}

/**
 * The plausible ratios in one model entry of the plugin's state file. Narrowed
 * with `in`/`typeof` rather than trusted: this extension does not own the file,
 * and an implausible ratio is provider bookkeeping, not text.
 */
function entryRatios(entry: unknown): number[] {
	if (typeof entry !== "object" || entry === null || !("ratios" in entry)) return [];
	const { ratios } = entry;
	if (!Array.isArray(ratios)) return [];
	return ratios.filter((value): value is number =>
		typeof value === "number" && Number.isFinite(value) &&
		value >= MIN_RATIO && value <= MAX_RATIO);
}

/**
 * Bytes per token learned by the `omp-tokrate` plugin, which is the only thing
 * on this machine that sees both streamed characters and the provider's final
 * `usage.output`. Reading its state file keeps that measurement in one place:
 * this extension publishes buckets and never calibrates, and a machine without
 * the plugin simply keeps the seed ratio.
 *
 * The ratio is a property of the model, so a value learned in the parent's TUI
 * session is the right one for a subagent that never paints a status line.
 */
export function createCalibrationLookup(
	read: (file: string) => string = (file) => fs.readFileSync(file, "utf8"),
): CharsPerTokenLookup {
	// A Map, not a Record: the keys are whatever models the plugin has met, the
	// table is rebuilt wholesale on every reload, and a `__proto__` key from a
	// file this extension does not own must stay inert.
	let ratios = new Map<string, number>();
	let loadedAt = Number.NEGATIVE_INFINITY;
	const load = (): void => {
		const next = new Map<string, number>();
		try {
			const parsed: unknown = JSON.parse(read(calibrationPath()));
			const models = typeof parsed === "object" && parsed !== null && "models" in parsed
				? parsed.models
				: undefined;
			if (typeof models === "object" && models !== null && !Array.isArray(models)) {
				for (const [key, entry] of Object.entries(models)) {
					const usable = entryRatios(entry);
					if (usable.length > 0) next.set(key, median(usable));
				}
			}
		} catch {
			// No plugin, no file yet, or a mid-write read: keep the seed ratio.
		}
		ratios = next;
	};
	return (model, provider) => {
		if (!model) return BYTES_PER_TOKEN;
		const now = Date.now();
		if (now - loadedAt >= CALIBRATION_TTL_MS) {
			loadedAt = now;
			load();
		}
		// `omp-tokrate` keys on `provider/id`, falling back to a bare id when the
		// stream named no provider.
		return ratios.get(provider ? `${provider}/${model}` : model) ?? ratios.get(model) ??
			BYTES_PER_TOKEN;
	};
}

function streamDelta(event: AssistantMessageEvent): string | undefined {
	switch (event.type) {
		case "text_delta":
		case "thinking_delta":
		case "toolcall_delta":
			return event.delta;
		default:
			return undefined;
	}
}

export default function tokenRate(api: ExtensionAPI): void {
	const buckets = new TokenRateBuckets(process.pid, createCalibrationLookup());
	const directory = runtimeDirectory();
	// One file per *session*, not per process. omp runs subagents in-process
	// and loads this extension again for each of their sessions, so a pid-keyed
	// file had N writers taking turns overwriting one another every 100 ms: the
	// meter saw whichever session published last, and a parent plus five
	// parallel scouts read as one stream. Separate files, and the meter's
	// per-file scan sums them exactly as it already does across processes.
	const target = path.join(directory, `${process.pid}-${crypto.randomUUID().slice(0, 8)}.json`);
	const temporary = `${target}.tmp`;
	let lastWrittenAt = 0;
	let dirty = false;

	const remove = (): void => {
		for (const file of [temporary, target]) {
			try {
				fs.unlinkSync(file);
			} catch (error) {
				if ((error as NodeJS.ErrnoException).code !== "ENOENT") api.logger.warn(`token-rate: ${String(error)}`);
			}
		}
	};

	// A session that dies without `session_shutdown` (kill -9, OOM, a crash)
	// leaves its file behind, and per-session names never get reused the way a
	// pid eventually is. The meter reads at most 128 files, so enough leftovers
	// would crowd out live ones. Each new session sweeps files whose owning
	// pid is gone; liveness is a signal-0 probe, and EPERM means "alive, not
	// ours", which is still alive.
	const sweep = (): void => {
		let entries: string[];
		try {
			entries = fs.readdirSync(directory);
		} catch {
			return;
		}
		for (const entry of entries) {
			const owner = Number.parseInt(entry, 10);
			if (!Number.isInteger(owner) || owner <= 0 || owner === process.pid) continue;
			try {
				process.kill(owner, 0);
				continue;
			} catch (error) {
				if ((error as NodeJS.ErrnoException).code !== "ESRCH") continue;
			}
			try {
				fs.unlinkSync(path.join(directory, entry));
			} catch (error) {
				if ((error as NodeJS.ErrnoException).code !== "ENOENT") api.logger.warn(`token-rate: ${String(error)}`);
			}
		}
	};
	sweep();

	const publish = (now: number, force = false): void => {
		if (!dirty || (!force && now - lastWrittenAt < BUCKET_MS)) return;
		try {
			fs.mkdirSync(directory, { recursive: true, mode: 0o700 });
			// 0644, not 0600: the protected herd panel reads these as its own
			// user through an ACL grant on the directory, and rename replaces the
			// inode every write, so a per-file grant could never stick. The
			// directory (0700 + ACL) is the access boundary, not the file bits.
			// chmod, because open() clamps its mode argument with the umask.
			fs.writeFileSync(temporary, JSON.stringify(buckets.snapshot(now)), { mode: 0o644 });
			fs.chmodSync(temporary, 0o644);
			fs.renameSync(temporary, target);
			lastWrittenAt = now;
			dirty = false;
		} catch (error) {
			api.logger.warn(`token-rate: ${String(error)}`);
		}
	};

	api.on("message_update", (event) => {
		const streamed = event.assistantMessageEvent;
		const delta = streamDelta(streamed);
		if (!delta) return;
		const now = Date.now();
		// Every streaming delta carries `partial: AssistantMessage`, whose
		// `provider` and `model` are the ones actually serving this generation —
		// the only attribution the extension is handed, and the one a reader needs
		// to tell a local generation (already counted at the GPU by the local
		// inference server) from a cloud one.
		buckets.ingest(delta, now, "partial" in streamed ? streamed.partial : undefined);
		dirty = true;
		publish(now);
	});
	api.on("message_end", () => publish(Date.now(), true));
	api.on("session_shutdown", () => remove());
}
