from pathlib import Path

import agents_sync as a


def make_cfg(tmp_path: Path) -> a.Config:
    repo = tmp_path / "repo"
    home = tmp_path / "home"
    (repo / "shared").mkdir(parents=True)
    (repo / "shared" / "AGENTS.md").write_text("# Shared core\nBody.\n")
    (repo / "shared" / "USER.md").write_text("# About the user\nFacts.\n")
    for agent in a.AGENTS:
        (repo / agent).mkdir()
        (repo / agent / "local.md").write_text(f"# {agent} delta\n")
    home.mkdir()
    return a.Config(repo=repo, home=home)


def test_targets_paths(tmp_path):
    cfg = make_cfg(tmp_path)
    paths = {t.agent: t.path for t in cfg.targets()}
    assert paths["claude"] == cfg.home / ".claude" / "CLAUDE.md"
    assert paths["codex"] == cfg.home / ".codex" / "AGENTS.md"
    assert paths["pi"] == cfg.home / ".pi" / "agent" / "AGENTS.md"
    assert paths["omp"] == cfg.home / ".omp" / "agent" / "AGENTS.md"


def test_compose_banner_shared_local_order(tmp_path):
    out = a.compose("codex", "SHARED\n", "LOCAL\n", [])
    assert out.startswith("<!-- GENERATED by agents-sync")
    assert "codex/local.md" in out.splitlines()[0]
    assert out.index("SHARED") < out.index("LOCAL")


def test_compose_skips_empty_local():
    out = a.compose("omp", "SHARED\n", "   \n", [])
    assert "SHARED" in out and out.count("\n\n") <= 2


def test_compose_puts_user_between_shared_and_local():
    body = a.compose("claude", "SHARED\n", "LOCAL\n", [], "USER\n").split("-->\n", 1)[1]
    assert body.index("SHARED") < body.index("USER") < body.index("LOCAL")


def test_expected_content_includes_user_md(tmp_path):
    cfg = make_cfg(tmp_path)
    t = [x for x in cfg.targets() if x.agent == "pi"][0]
    exp = a.expected_content(cfg, t)
    assert exp.index("# Shared core") < exp.index("# About the user") < exp.index("# pi delta")


def test_expected_content_without_user_md(tmp_path):
    cfg = make_cfg(tmp_path)
    cfg.user_md.unlink()
    t = [x for x in cfg.targets() if x.agent == "pi"][0]
    assert "# About the user" not in a.expected_content(cfg, t)


def test_extract_foreign_blocks_roundtrip():
    block = "<!-- fetcher:begin (managed) -->\n## Fetch\nuse fetch\n<!-- fetcher:end -->\n"
    text = "junk\n" + block + "more junk\n"
    assert a.extract_foreign_blocks(text) == [block]


def test_compose_appends_foreign_blocks():
    block = "<!-- fetcher:begin -->\nX\n<!-- fetcher:end -->\n"
    out = a.compose("pi", "SHARED\n", "LOCAL\n", [block])
    assert out.rstrip("\n").endswith("<!-- fetcher:end -->")
    assert out.index("LOCAL") < out.index("fetcher:begin")


def test_expected_content_preserves_existing_foreign_block(tmp_path):
    cfg = make_cfg(tmp_path)
    t = [x for x in cfg.targets() if x.agent == "codex"][0]
    t.path.parent.mkdir(parents=True)
    t.path.write_text("old stuff\n<!-- fetcher:begin -->\nF\n<!-- fetcher:end -->\n")
    exp = a.expected_content(cfg, t)
    assert "fetcher:begin" in exp and "old stuff" not in exp
    assert "# Shared core" in exp and "# codex delta" in exp


def test_target_state_all_four(tmp_path):
    cfg = make_cfg(tmp_path)
    t = [x for x in cfg.targets() if x.agent == "claude"][0]
    exp = a.expected_content(cfg, t)
    assert a.target_state(t, exp) == "missing"
    t.path.parent.mkdir(parents=True)
    t.path.write_text(exp)
    assert a.target_state(t, exp) == "clean"
    t.path.write_text(exp + "\nhand edit\n")
    assert a.target_state(t, exp) == "drifted"
    t.path.write_text("# my own file, no banner\n")
    assert a.target_state(t, exp) == "foreign"
